### ISSUE TITLE
Route Navigation/Assistant audio through BT when ‘disable audio sink’ is enabled

### ISSUE THREAD

**Issue by osunick** [cpebit/aawireless-issues#84] opened 2021-09-20 06:34 UTC
My car has a retrofitted android auto/carplay unit that uses AUX for audio. Bluetooth audio would be much cleaner and enable physical controls.

**Comment by Snirpo** [comment] 2022-02-02 14:15
Duplicate of #59

**Closed by Snirpo** 2022-02-02 14:15 UTC
