### ISSUE TITLE
Xiaomi MIUI > 12.5: Connection drop when mobile network switch/disconnects

### ISSUE THREAD

**Issue by blfarkas** [cpebit/aawireless-issues#102] opened 2022-03-21 12:48 UTC
**Describe the bug**
When driving and signal (mobile data) drops, Android Auto disconnects and connects again. It's a bit annoying when driving on country roads or motorway. On MIUI I enabled setting (keep mobile data always enabled) for faster connection switching in developer options and in Wi-Fi settings I've tried all the settings (even extreme mode). Issue still persists. 

**Screenshots**
N/A

**Car (please complete the following information):**
- Ford Focus MK3.5, 2018

**Headunit (please complete the following information):**
- Ford Sync 3

**Smartphone (please complete the following information):**
 - Xiaomi Mi 10 5G
 - Android version 11
 - MIUI 12.5.8

**Additional context**
N/A

**Comment by RonnyJakobsson** [comment] 2022-03-23 10:56
Have exactly the same issue on Xiaomi 11 
Super annoying. Have tried to disable everything that automatically change internet connection. 

When loosing connection the Aawireless app switches Bluetooth to the Aadevices dummy bluetooth audio and you voice call is interrupted. So when expecting an important phone call i have to unplug the Aawireless.

**Comment by blfarkas** [comment] 2022-03-23 11:18
I think dummy bluetooth feature will be disabled in AAWireless version 2.0.0 as far as I understood. See update from 2nd of March, 2022 [HERE](https://www.indiegogo.com/projects/aawireless#/updates/all)

**Comment by Snirpo** [comment] 2022-03-23 14:33
Yes, but this will not fix the problem with mobile connection drop == wifi drop. This is an Xiaomi issue which we cannot fix.

**Comment by Dehumanizer77** [comment] 2022-03-23 21:12
I have the exactly same problem. Easiest way to demonstrate it is to disable mobile data when connected to the aawireless. It disconnects immediately.
So essentially, aawireless is unusable with Xiaomi phones and it will not be fixed? You should yhen explicitly say that AAwireless does not work with Xiaomi phones. 
This really sucks.

**Comment by Dehumanizer77** [comment] 2022-03-23 21:31
By the way, wifi DOES NOT disconnect when this happens, it stays connected all the time, I was specifically watching this. The onboard display reports USB disconnect, so it's between AAwireless and car, plus I am almost sure that this issue was not present in older firmware versions, so I think there is something you can do.

**Comment by Snirpo** [comment] 2022-03-24 08:18
Unfortunately we cannot fix issues in the firmware of the phone. We can downgrade your firmware of the device if you want to test.

**Comment by Snirpo** [comment] 2022-03-24 08:32
Has just been confirmed by one of our testers: update to MIUI 12.5.x broke it. I'll get one myself to verify.

**Comment by Dehumanizer77** [comment] 2022-03-24 18:54
If you have a chance to test MIUI 13 (which is android 12) if it works, I'd appreciate it... As I might consider upgrading if it works in 13.

**Comment by blfarkas** [comment] 2022-03-24 19:45
I've updated system on my Mi 10 to MIUI 13 (Android 12) and issue still persists. Just FYI

**Comment by Dehumanizer77** [comment] 2022-03-25 06:17
That's unfortunate, and for me it's really unusable, as my operator uses national roaming and every time the network switches, it disconnects. Even when a phone starts ringing it immediatelly disconnects.
If there is a way to downgrade the firmware, I'd be glad to test it.

**Comment by Snirpo** [comment] 2022-03-30 18:38
@Dehumanizer77 Sorry, just saw this. Please join us on Slack. I can explain how to downgrade.

Join my Slack workspace! https://join.slack.com/t/aawireless/shared_invite/zt-nu6jokgj-Y~FxA6aegEZMi98aISYEjA

**Comment by Dehumanizer77** [comment] 2022-03-31 08:05
I have just tried older firmware and the problem is still there so I just might be lucky before that I didn't get any disconnects. 
Anyway, the good news is that in some latest MIUI 13 beta it's reported working so I hope if we'll just wait, it will be working in stable version soon (or you can try beta).

**Comment by pacogeno1** [comment] 2022-03-31 08:16
Ok me atrevo a probar la versión beta , como debo de hacerlo. ¿??Gracias

De: JoHnY ***@***.***> 
Enviado el: jueves, 31 de marzo de 2022 10:08
Para: cpebit/aawireless-issues ***@***.***>
CC: pacogeno1 ***@***.***>; Manual ***@***.***>
Asunto: Re: [cpebit/aawireless-issues] Connection drop when mobile network switch/disconnects (Issue #102)

 

@blfarkas <https://github.com/blfarkas>  if you are brave enough to try the latest beta, please let us know if it worked for you as well :-) I guess I'll just wait a bit if it will make its way into stable version.

**Comment by Snirpo** [comment] 2022-03-31 08:20
Verified with @Dehumanizer77, downgrading firmware to 1.7.1 does not fix this issue.
I haven't got my Mi10 yet to verify, but pretty sure this is an Xiaomi issue:

https://xiaomi.eu/community/threads/mi11-ultra-with-miui-13-stable-wireless-android-auto-cant-connect.64766/

**Comment by Dehumanizer77** [comment] 2022-03-31 13:43
@pacogeno1 Just try any latest MIUI 13 beta from xiaomi.eu , but if you don't know how, you shouldn't probably do it or you might brick your phone.

**Comment by SoapWater** [comment] 2022-04-21 14:19
Hi all,
I've also the problem with my mi smartphone. Sadly I own AAwireless for a couple of months but it just lays around in the glove box because it makes no sense to use it because of this problem. As I only want to use official ROM, I'm not able to test the xiaomi.eu beta builds.

@Snirpo did you already check if firmware 2 won't fix this problem by disabling the Bluetooth dummy? Or was it just a guess?

Kind regards :)

**Comment by Snirpo** [comment] 2022-04-26 06:25
I did not test yet. I do have a Mi10 now. Hopefully we have some time next week to test.

**Comment by pacogeno1** [comment] 2022-04-26 16:56
> Si tiene la oportunidad de probar MIUI 13 (que es Android 12) si funciona, se lo agradecería... Ya que podría considerar actualizar si funciona en 13.

He probado con MIUI 13 y Android 12 en Xiaomi MI 10 y se sigue desconectando el AA Wirelles de la consola del coche con Android auto , y al poco tiempo vuelve de nuevo a conectarse . Es muy incomoda esta situcion al final decides conectar el movil a la consola del coche con cable y pasr del AAWieless

**Comment by lalo-nrgz** [comment] 2022-05-05 08:04
I a having similar trouble with my unit with a Toyota RAV4 2021 + Samsung S20 unrooted, stock rom.

I get random connection drops, and sometimes it is unable to reconnect. I had to change the USB mode to MTP when I made the setup as on default profile I was unable to set the connection (nothing was happening on the car headunit).

I still have to apply the 2.0 update and test the Bixby Routines to force the "Home button" press & keeping the wifi connection active whilst it is connected to the bluetooth dongle.

Any clues about what to try next?

**Comment by juanfdp** [comment] 2022-05-05 15:15
> Most likely interference issues in your case. 2.0 firmware will make the wifi channel selectable which should help.

Hi all, I have been testing version 2 of the firmware for two weeks, the first thing I did was put the manual channel number in the wifi settings section and put it in 2.4 ghz mode, with that the connection became more stable

**Comment by SoapWater** [comment] 2022-05-06 08:20
> I did not test yet. I do have a Mi10 now. Hopefully we have some time next week to test.

Hi, I just received the firmware 2 update and tested it myself. Sadly it didn't help. So I have either to wait another years for Xiaomi to fix it or buy a new phone...

**Comment by Snirpo** [comment] 2022-05-09 10:52
@lalo-nrgz The issue you are talking about is completely unrelated to this issue. This issue is specific to Xiaomi phones.

Are these disconnections actually random? It's quite possible they seem random but they are actually happening at the same location everytime. In that case use 5Ghz wifi and switch to a higher channel from the wifi settings in the app.

If they are random, please push a bug report via the app. What's the name of your device?

Also, this is no support section, we are doing the best we can. Random disconnections are the most difficult issue to solve. It could be anything bassiccly. Could be hardware, could be phone related, could be head unit related.

**Comment by lalo-nrgz** [comment] 2022-05-09 10:59
> @lalo-nrgz The issue you are talking about is completely unrelated to this issue. This issue is specific to Xiaomi phones.
> 
> Are these disconnections actually random? It's quite possible they seem random but they are actually happening at the same location everytime. In that case use 5Ghz wifi and switch to a higher channel from the wifi settings in the app.
> 
> If they are random, please push a bug report via the app. What's the name of your device?
> 
> Also, this is no support section, we are doing the best we can. Random disconnections are the most difficult issue to solve. It could be anything bassiccly. Could be hardware, could be phone related, could be head unit related.

Thanks for your answer and sorry if this thread was only for Xiaomi phones, that not what I understood. My apologies.

My device is iHn5uhRq, I will push a bug report later in the afternoon. I understand that the disconnections have a reason and something is causing them, they are not really random, but they do not seem to be location-based, as I have tested it several days on my way to/from work (50 kms and 35-50 minutes, same route everyday forth and back) and sometimes it does not disconnect, sometimes only one time and on some other times (as today) it drops 4 times on different points of the route and it does not connect back :(

If there is anything else I can do to help you and others about this, please just let me know,

**Comment by Snirpo** [comment] 2022-05-20 10:11
Finally had the time to verify this issue on the MI10. I can reproduce it. When mobile data is disabled, and enabled again, the phone will drop the Android Auto connection. It will reconnect very fast though. We are going to try to downgrade to an older MIUI version and verify.

**Comment by Dehumanizer77** [comment] 2022-05-20 10:28
The problem is also that this (depending on the carrier and network properties etc.) also happens when you either receive a phone call or initiate a phone call which essentially makes calling unusable.

**Comment by maex-la** [comment] 2022-05-21 10:27
I have the same issue with Xiaomi 12x EU official Rom, Android 12 and MIUI Global 13.02.
If the guys from AAWireless can't help, all we can do, I guess, is to send bug- notifications in masses to Xiaomi to get some pressure on them to solve it.
Or are there other things we can try meanwhile?

**Comment by maex-la** [comment] 2022-05-21 11:08
Other idea:
As I understood from the postings above loosing the mobile network causes Xiaomi phones to close WiFi connection, causes AAWireless to close USB connection. Right?
Could pe a possibility to give the option in settings to keep USB connection for a few seconds after loosing WiFi, because this lasts normally only for short time (the connections are all re-established in seconds now).

**Comment by jan-sindelar** [comment] 2022-05-21 11:55
I have AAWireless just few days, firmware 2.0 and I have same disconnections issue. It is not random, it happens exactly at the same spots during my daily routes to work. I have Google Pixel 3a (Android 12), so I think it is not just Xiaomi related problem. Sometimes it reconnects automatically (after 30 seconds or more), sometimes I have to unplug AAWireless completely and plug it in again to re-establish connection. It is really annoying.

**Comment by Snirpo** [comment] 2022-05-21 12:31
@jan-sindelar completely different issue. Please change to a higher wifi channel. And please update to firmware 2.0.1 to solve the connection not restarting in the event of a connection drop (for some reason).

**Comment by Snirpo** [comment] 2022-05-24 07:12
Just tested this issue on Motorola MA1, same exact issue. So unfortunately we cannot fix this.

**Closed by Snirpo** 2022-05-24 07:12 UTC

**Comment by maex-la** [comment] 2022-06-14 20:16
I am already in contact with Xiaomi support via Settings/Services and Feedback on the phone.
Would be helpfull more Xiaomi-users giving them feedback concerning this bug!

**Comment by Dehumanizer77** [comment] 2022-06-16 09:08
@maex-la I just did send them a feedback on the issue. Did they respond to you in some way? What did they say?

**Comment by maex-la** [comment] 2022-06-16 10:03
They told that they received the log. I shall be patient while they analyse it...

**Comment by Rubeast** [comment] 2022-07-31 06:12
I see that this issue is closed, but I fail to see what the solution is. I also have a Xiaomi phone where aawireless constantly disconnects and can't do phone calls. Can be reproduced by turning mobile data off and then back on.

**Comment by Dehumanizer77** [comment] 2022-07-31 06:26
> I see that this issue is closed, but I fail to see what the solution is. I also have a Xiaomi phone where aawireless constantly disconnects and can't do phone calls. Can be reproduced by turning mobile data off and then back on.

It's a Xiaomi issue and they don't seem to care, probably not enough Xiaomi users don't use wireless android auto, otherwise I don't know why they are ignoring it. It's not aawireless specific, it happens on MIUI also in cars with built-in wireless android auto connection. Send them a report.

**Comment by blfarkas** [comment] 2023-01-11 08:31
Hey guys.

Yesterday, due to this issue, I decided to move to clean Android (PixelExperience ROM) instead of MIUI for my Xiaomi Mi 10.
This issue is now completely gone, so it is definetely 100% an MIUI issue.
And also I've read from guys who already upgraded to MIUI 14 (based on Android 13) that the issue is still present on their devices.

So if you want to have this issue fixed just switch to another ROM or buy a new phone without MIUI 😄 

Cheers!

**Comment by Dehumanizer77** [comment] 2023-01-11 08:57
Yes, I have upgraded to Pixel Experience too several months ago and it works fine.
