### ISSUE TITLE
Start / Stop setting cannot be enabled

### ISSUE THREAD

**Issue by seva-luchianov** [cpebit/aawireless-issues#104] opened 2022-04-18 04:41 UTC
After updating the app to v2.1.0, the start / stop setting can no longer be enabled. While connected to the aawireless unit, I will go into settings, select start / stop. I toggle it on and then select my car's Bluetooth. After I exit that settings screen, start / stop still shows as disabled.
Firmware v1.8
Start / stop used to work in the previous version of the app. Updating the app seemed to reset all settings to default values.

**Comment by nlibby987** [comment] 2022-04-18 14:14
I am having the same issue, just email support then saw this.

**Comment by Snirpo** [comment] 2022-04-18 14:57
Confirmed, fixing it. Back to defaults is odd though. All settings went back to defaults?

**Comment by seva-luchianov** [comment] 2022-04-18 15:01
I'm not sure if it was all of them, since the only settings I had changed from their default value before the update were start / stop enabled, and passthrough mode enabled. Both of them reverted to disabled after the update. I also had to regrant the nearby devices permission to the app after updating.
Android 12 on Pixel 6 Pro if that helps.

**Comment by nlibby987** [comment] 2022-04-18 15:04
Confirmed, exact same situation. I also have a pixel 6 pro and on 12. Playthrough needed to be enabled and start/stop but those were the only settings I had changed.

**Comment by seva-luchianov** [comment] 2022-04-18 15:06
Heh, @nlibby987 what are the odds you also drive a Subaru WRX

**Comment by nlibby987** [comment] 2022-04-18 15:28
Nope lol, Mazda 3

**Comment by Snirpo** [comment] 2022-04-18 19:33
Start / stop screen is fixed in 2.2.0, pushing to play store right now. But we still have bluetooth connectivity issues which I'm researching :(

**Comment by seva-luchianov** [comment] 2022-04-18 19:44
I've never experienced any connectivity issues, the only weirdness I've had is with discord audio playing through the phone instead of the head unit. I had the same issue intermittently with phone audio as well, but that was fixed by enabling passthrough mode. Discord will always play through the phone only.

**Comment by nlibby987** [comment] 2022-04-18 19:47
I haven't had any connectivity issues with Bluetooth, but I have playthrough enabled because if it is not the car seems to disconnect from the Adapter every 5 min or so but with playthrough enabled it works great.

**Comment by seva-luchianov** [comment] 2022-04-18 19:49
From what I understand firmware 2.0 might address the audio issue by getting rid of the dummy bt profile, but I dunno about the connectivity issues.

**Comment by Snirpo** [comment] 2022-04-18 20:07
I mean connectivity issues with the app. Not being able to fetch or save the settings.

**Comment by seva-luchianov** [comment] 2022-04-18 20:08
Ah my mistake. Ty for pushing a fix so fast for start stop!

**Comment by Jarvikless** [comment] 2022-04-20 11:27
Uconnect 4 12" display using Pixel 5 and the AA wireless 1.8 from Google Play store and start/stop is not functioning. I've tried updating and/or downloading from Play but problem persists.

**Comment by Snirpo** [comment] 2022-04-26 06:23
Should be fixed in app 2.2.0 and higher.

**Closed by Snirpo** 2022-04-26 06:23 UTC
